DROP PROCEDURE SELECT_ALL;
DELIMITER //
CREATE PROCEDURE SELECT_ALL()

BEGIN
	DECLARE T INT;
	DECLARE D INT;
    DECLARE H INT;
    DECLARE M INT;
    DECLARE S INT;
    SET T = 123456;
    SET D = FLOOR(T / 86400);
    SET T = T - (D * 86400);
    SET H = FLOOR(T / 3600);
    SET T = T - (H * 3600);
    SET M = FLOOR(T / 60);
    SET S = T - M * 60;
    SELECT D, H, M, S;    
END//

DELIMITER ;
CALL SELECT_ALL();

DROP PROCEDURE EVEN;
DELIMITER //
CREATE PROCEDURE EVEN()

BEGIN
	DECLARE NUM INT;
    DECLARE RESULT VARCHAR(45);
    DROP TABLE NUMB;
    CREATE temporary TABLE NUMB
    (
		T int
    );
    SET NUM = 2;
    SET RESULT =' ';
	WHILE NUM <= 10 DO
		INSERT NUMB VALUES (NUM);
		SET NUM = NUM + 2;
    END WHILE;
	SELECT T FROM NUMB;
END//

DELIMITER ;
CALL EVEN();